core/blog/urls.py
from django.urls import path

from .views import PostListView, PostDetailView

app_name = "blog"

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path("cart/", include("cart.urls")),
    path("shop/", include("shop.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from taggit.managers import TaggableManager

User = get_user_model()


class Category(models.Model):
    """
    Represents a category for blog posts.
    """

    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"
        # verbose_name = "Categorie"

    def __str__(self):
        """Returns the string representation of the category name."""
        return self.name


class Post(models.Model):
    """
    Represents a blog post.
    """

    title = models.CharField(max_length=200)
    # slug = models.SlugField(unique=True, max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=0)
    content = models.TextField()
    image = models.ImageField(
        upload_to="blog/", default="blog/default.jpg", null=True, blank=True
    )
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    counted_views = models.IntegerField(default=0)
    login_require = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        """Returns the string representation of the post title."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a specific post."""
        return reverse("blog:single", kwargs={"pid": self.pk})


class Comment(models.Model):
    """
    Represents a comment on a blog post.
    """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=100)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    comment = models.TextField()
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a string representation of the comment along with commenter's name and post title."""
        return f"Comment by {self.name} on {self.post.title}"

core/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "website", "comment"]

core/blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.utils.dateparse import parse_date
from django.shortcuts import redirect

from .models import Category, Post
from .forms import CommentForm


class PostListView(ListView):
    model = Post
    paginate_by = 12
    context_object_name = "posts"
    template_name = "blog/post_list.html"

    def get_queryset(self):
        queryset = Post.objects.filter(status=True)
        q = self.request.GET.get("q")
        category = self.request.GET.get("category")
        author = self.request.GET.get("author")
        tag = self.request.GET.get("tag")
        date_str = self.request.GET.get("date")

        if q:
            queryset = queryset.filter(Q(title__icontains=q) | Q(content__icontains=q))
        if category:
            queryset = queryset.filter(category__name__iexact=category)
        if author:
            queryset = queryset.filter(author__profile__first_name__iexact=author)
        if tag:
            queryset = queryset.filter(tags__slug__iexact=tag)
        if date_str:
            date = parse_date(date_str)
            if date:
                queryset = queryset.filter(
                    created_at__year=date.year,
                    created_at__month=date.month,
                    created_at__day=date.day,
                )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["recent_posts"] = Post.objects.filter(status=True).order_by(
            "-created_at"
        )[:3]
        # context['tags'] = Tag.objects.all()  # only if using taggit
        return context


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object

        # Add comment form
        context["form"] = CommentForm()

        # Get approved comments
        context["comments"] = post.comments.filter(approved=True).order_by(
            "-created_at"
        )

        # Get previous and next posts
        context["prev_post"] = (
            Post.objects.filter(status=True, created_at__lt=post.created_at)
            .order_by("-created_at")
            .first()
        )

        context["next_post"] = (
            Post.objects.filter(status=True, created_at__gt=post.created_at)
            .order_by("created_at")
            .first()
        )

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.object
            comment.save()
            return redirect(self.request.path_info)

        # If invalid form, re-render with errors
        context = self.get_context_data()
        context["form"] = form
        return self.render_to_response(context)

core/templates/blog/blog_category.html
<aside class="single_sidebar_widget post_category_widget">
  <h4 class="widget_title">Category</h4>
  <ul class="list cat-list">
    {% for category in categories %}
    <li>
      <a href="{% url 'blog:post-list' %}?category={{ category.name }}" class="d-flex">
        <p>{{ category.name }}</p>
        <p>({{ category.post_set.count }})</p>
      </a>
    </li>
    {% endfor %}
  </ul>
</aside>

core/templates/blog/blog_latest_posts.html
<!-- Latest Postd Start -->
<section class="latest-product-area padding-bottom">
  <div class="container">
    <div class="row product-btn d-flex justify-content-end align-items-end">
      <!-- Section Tittle -->
      <div class="col-xl-4 col-lg-5 col-md-5">
        <div class="section-tittle mb-30">
          <h2>Latest Posts
          </h2>
        </div>
      </div>
    </div>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="row">
          {% for post in latest_posts %}
          <div class="col-xl-4 col-lg-4 col-md-6">
            <div class="single-product mb-60">
              <div class="product-img">
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
              </div>
              <div class="product-caption">
                <h4>
                  <a href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a>
                </h4>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Latest Postd End -->

core/templates/blog/blog_recent_post.html
<aside class="single_sidebar_widget popular_post_widget">
  <h3 class="widget_title">Recent Posts</h3>
  {% for post in recent_posts %}
  <div class="media post_item">
    <img src="{{ post.image.url }}" alt="{{ post.title }}" width="100" height="70">
    <div class="media-body">
      <a href="{% url 'blog:post-detail' post.pk %}">
        <h3>{{ post.title|truncatewords:6 }}</h3>
      </a>
      <p>{{ post.created_at|date:"F j, Y" }}</p>
    </div>
  </div>
  {% endfor %}
</aside>

core/templates/blog/blog_search.html
<aside class="single_sidebar_widget search_widget">
  <form action="{% url 'blog:post-list' %}" method="get">
    <div class="form-group">
      <div class="input-group mb-3">
        <input type="text" name="q" class="form-control" placeholder="Search Keyword"
               onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">
        <div class="input-group-append">
          <button class="btns" type="submit"><i class="ti-search"></i></button>
        </div>
      </div>
    </div>
    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn" type="submit">Search</button>
  </form>
</aside>

core/templates/blog/blog_tags.html
<aside class="single_sidebar_widget tag_cloud_widget">
  <h4 class="widget_title">Tag Clouds</h4>
  <ul class="list">
    {% for tag in post.tags.all %}
    <li>
      <a href="{% url 'blog:post-list' %}?tag={{ tag.slug }}">{{ tag.name }}</a>
      {% empty %}
      No tags
    </li>
    {% endfor %}
  </ul>
</aside>

core/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load humanize %}

    <!-- slider Area Start-->
    <div class="slider-area ">
      <!-- Mobile Menu -->
      <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'img/hero/category.jpg' %}">
          <div class="container">
              <div class="row">
                  <div class="col-xl-12">
                      <div class="hero-cap text-center">
                          <h2>{{post.title}}</h2>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- slider Area End-->
     
   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{ post.image.url }}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{post.title}}</h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="{% url 'blog:post-list' %}?author={{ post.author.profile.first_name }}"><i class="fa fa-user"></i> {{post.author.profile.first_name}}</a></li>
                        <li><a href="#"><i class="fa fa-comments"></i> {{post.comments.count}} Comments</a></li>
                     </ul>
                     <p class="excert">{{ post.content }}</p>
                  </div>
               </div>
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <p class="like-info"><span class="align-middle"><i class="fa fa-heart"></i></span> Lily and 4
                        people like this</p>
                     <div class="col-sm-4 text-center my-2 my-sm-0">
                        <!-- <p class="comment-count"><span class="align-middle"><i class="fa fa-comment"></i></span> 06 Comments</p> -->
                     </div>
                     <ul class="social-icons">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fab fa-behance"></i></a></li>
                     </ul>
                  </div>
                  <div class="navigation-area">
                     <div class="row">

                        {# Prev Post #}
                        {% if prev_post %}
                        <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                           <div class="thumb">
                           <a href="{% url 'blog:post-detail' prev_post.pk %}">
                              <img class="img-fluid" src="{{ prev_post.image.url }}" alt="{{ prev_post.title }}" width="100" height="100">
                           </a>
                           </div>
                           <div class="arrow">
                           <a href="{% url 'blog:post-detail' prev_post.pk %}">
                              <span class="lnr text-white ti-arrow-left"></span>
                           </a>
                           </div>
                           <div class="detials">
                           <p>Prev Post</p>
                           <a href="{% url 'blog:post-detail' prev_post.pk %}">
                              <h4>{{ prev_post.title|truncatewords:5 }}</h4>
                           </a>
                           </div>
                        </div>
                        {% endif %}

                        {# Next Post #}
                        {% if next_post %}
                        <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                           <div class="detials">
                           <p>Next Post</p>
                           <a href="{% url 'blog:post-detail' next_post.pk %}">
                              <h4>{{ next_post.title|truncatewords:5 }}</h4>
                           </a>
                           </div>
                           <div class="arrow">
                           <a href="{% url 'blog:post-detail' next_post.pk %}">
                              <span class="lnr text-white ti-arrow-right"></span>
                           </a>
                           </div>
                           <div class="thumb">
                           <a href="{% url 'blog:post-detail' next_post.pk %}">
                              <img class="img-fluid" src="{{ next_post.image.url }}" alt="{{ next_post.title }}" width="100" height="100">
                           </a>
                           </div>
                        </div>
                        {% endif %}

                     </div>
                  </div>

               </div>
               <div class="blog-author">
                  <div class="media align-items-center">
                     <img src="{% static 'img/blog/author.png' %}" alt="">
                     <div class="media-body">
                        <a href="#">
                           <h4>{{ post.author.profile.first_name }}</h4>
                        </a>
                        <p>{{ post.author.profile.bio }}</p>
                     </div>
                  </div>
               </div>
               <div class="comments-area">
               <h4>{{ comments.count }} Comment{{ comments.count|pluralize }}</h4>
               {% for comment in comments %}
               <div class="comment-list">
                  <div class="single-comment justify-content-between d-flex">
                     <div class="user justify-content-between d-flex">
                     <div class="thumb">
                        <img src="{% static 'img/comment/comment_1.png' %}" alt="">
                     </div>
                     <div class="desc">
                        <p class="comment">{{ comment.comment }}</p>
                        <div class="d-flex justify-content-between">
                           <div class="d-flex align-items-center">
                           <h5><a href="#">{{ comment.name }}</a></h5>
                           <p class="date">{{ comment.created_at|naturaltime }}</p>
                           </div>
                        </div>
                     </div>
                     </div>
                  </div>
               </div>
               {% endfor %}
               </div>

               <div class="comment-form">
                  <form class="form-contact comment_form" action="." method="POST" id="commentForm">
                     {% csrf_token %}
                     <div class="row">
                        <div class="col-12">
                           <div class="form-group">
                              <textarea class="form-control w-100" name="comment" id="comment" cols="30" rows="9"
                                 placeholder="Write Comment"></textarea>
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="name" id="name" type="text" placeholder="Name">
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="email" id="email" type="email" placeholder="Email">
                           </div>
                        </div>
                        <div class="col-12">
                           <div class="form-group">
                              <input class="form-control" name="website" id="website" type="text" placeholder="Website">
                           </div>
                        </div>
                     </div>
                     <div class="form-group">
                        <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message</button>
                     </div>
                  </form>
               </div> 
            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">
                  
                        {% include "blog/blog_search.html" %}

                        {% include "blog/blog_tags.html" %}
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->
{% endblock %}

core/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'img/hero/category.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Blog</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% for post in object_list %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{ post.image.url }}" alt="{{post.title}}">
                                <a href="{% url 'blog:post-list' %}?date={{ post.created_at|date:"Y-m-d" }}" class="blog_item_date">
                                    <h3>{{ post.created_at|date:"j" }}</h3>
                                    <p>{{ post.created_at|date:"F" }}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'blog:post-detail' post.pk %}">
                                    <h2>{{post.title}}</h2>
                                </a>
                                <p>{{ post.content|truncatewords:30 }}</p>
                                <ul class="blog-info-link">
                                    <li><a href="{% url 'blog:post-list' %}?author={{ post.author.profile.first_name }}"><i class="fa fa-user"></i>{{post.author.profile.first_name}}</a></li>
                                    <li><a href="{% url 'blog:post-detail' post.pk %}"><i class="fa fa-comments"></i> {{post.comments.count}} Comments</a></li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}
                        <nav class="blog-pagination justify-content-center d-flex">
                        {% if is_paginated %}
                        <ul class="pagination">

                            {# Previous Page Link #}
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a href="#" class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                            </li>
                            {% endif %}

                            {# Page Numbers #}
                            {% for num in paginator.page_range %}
                                {% if num == page_obj.number %}
                                    <li class="page-item active">
                                        <a href="#" class="page-link">{{ num }}</a>
                                    </li>
                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <li class="page-item">
                                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {# Next Page Link #}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a href="#" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                            {% endif %}

                        </ul>
                        {% endif %}
                        </nav>

                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">

                        {% include "blog/blog_search.html" %}

                        {% include "blog/blog_category.html" %}
                        
                        {% include "blog/blog_recent_post.html" %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->

{% endblock %}